### ISSUE TITLE
Routing of URLs with extensions

### ISSUE THREAD

**Issue by djanosik** [aspnet/Routing#170] opened 2015-03-23 12:00 UTC
Hi,

I have an application with URLs with extensions (eg. `http://app.com/eZ6Vwe.m`). When the URL does not end with `/` (slash) it sometimes returns 404. But sometimes it works. I don't understand why. Can you help me to find out where is the problem?

Thank you!

**Comment by rynowak** [comment] 2015-03-23 17:01
Can you please provide us with a small repro project and some examples of cases that do and do not work so we can investigate?

**Comment by djanosik** [comment] 2015-03-23 18:31
Of course, here it is: http://leteckaposta.cz/698960507

1. Open solution in VS 2015 CTP 6
2. Start project without debugging
3. Go to `/hash.m` => should work
4. Rebuild the solution (do not stop the application)
5. Go again to `/hash.m` => returns 404

The following URLs work as expected:

- `/hash.m/` (with ending slash)
- `/hash:m`
- `/hash:m/`

**Comment by rynowak** [comment] 2015-03-23 18:46
Would it be possible to share a repo link or a gist of the startup code? I'm having trouble getting the zip download to work.

**Comment by djanosik** [comment] 2015-03-23 18:53
I've updated the [link](http://moontea.net/routewithextension.zip). Can you download it now?

**Comment by rynowak** [comment] 2015-03-23 18:59
Working now, thanks.

**Comment by rynowak** [comment] 2015-03-23 19:11
Do you encounter any routing problems when you **don't** rebuild while the sever is running?

Do you encounter any routing problems after restarting the server? (It sounds like all of your issues go away if you restart the site).

I'm suspecting this is a tooling/timing issue because I am unable to reproduce it locally on my VS build (which is newer). If there's no routing problem in steady-state then I'm going to move this bug to the tooling repo and those folks should be able to provide you more information.

**Comment by djanosik** [comment] 2015-03-23 20:03
It doesn't help to restart the site. Actually it seems it stops working after the restart. I've tried to restart an application running on full IIS on Azure and it stopped working. I can restart IIS Express and it helps. But it's only temporary solution. After I make some changes, it stops working again.

I cannot say right now whether it happens when I don't make any changes while the application is running.

**Comment by djanosik** [comment] 2015-03-23 22:01
Ok it seems there are no routing problems when I don't rebuild, restart or change the site while it is running.

**Comment by rynowak** [comment] 2015-03-23 22:21
Thanks. I'm going to close this bug and re-open on tooling so they can get to the bottom of this.

**Comment by rynowak** [comment] 2015-03-23 22:23
Copied to https://github.com/aspnet/Tooling/issues/33

**Closed by rynowak** 2015-03-23 22:23 UTC
