### ISSUE TITLE
AttributeRouting - Route Template - Changed Behavior?

### ISSUE THREAD

**Issue by dneimke** [aspnet/Routing#247] opened 2015-12-08 01:31 UTC
In our Api, we have an Attribute route with a template that looks like this:

```
[Route("{something}/foo")]
public IAction GetStuff(int something) { ... }
```

This previously worked fine but now the Route is no longer matched.  

Has the default Routing behavior changed so that named tokens are no longer matched automagically?

**Comment by dneimke** [comment] 2015-12-08 01:37
I thing I worked it out.  It appears that the behavior is now stricter in that you have to specify the type of the token:

e.g.: THIS WORKS:
```
[Route("{something:int}/foo")]
public IAction GetStuff(int something) { ... }
```

**Comment by rynowak** [comment] 2015-12-08 01:41
Can you provide a more complete code sample? We didn't make any intentional behavior changes here.

**Comment by dneimke** [comment] 2015-12-08 02:34
I don't have time to set up a canonical repro, but what we have is essentially this:

```
[Route("api/myentity")]
public class MyEntityController : MyBaseController<MyEntity>
{
    [Route("{something}/foo")]
    public IAction GetStuff(int something) { ... }
}
```

This worked fine previously by now requires the type descriptor to be applied to '{something}'.

It's odd because Swagger finds it and accurately displays the GET route, but when we invoke calls against it, the default routing provider is unable to find the route so it falls through to our default app.Run catch all handler.

**Comment by dneimke** [comment] 2015-12-08 04:09
Further info...

It appears to be only an issue where the token is not at the end of the route template.

E.g.

```
//OK
[Route("foo/{something}")]

//NOT OK
[Route("{something}/foo")]
```

**Comment by rynowak** [comment] 2015-12-08 16:47
Thanks, I'll take a look at this

**Comment by rynowak** [comment] 2015-12-10 16:31
So I tried this out on newest bits and I am able to hit this action:

http://localhost:23687/api/myentity/5/foo
```
    [Route("api/myentity")]
    public class MyEntityController : Controller
    {
        [Route("{something}/foo")]
        public IActionResult GetStuff(int something)
        {
            return Content("Hello");
        }
    }
```

Can you provide more information?

Is there a github repo I can look at? What version of MVC?

**Comment by Eilon** [comment] 2015-12-30 00:32
Closing because we cannot reproduce this. If you see this on a new build of ASP.NET 5 / MVC 6 please re-open or log a new issue.

**Closed by Eilon** 2015-12-30 00:32 UTC
