### ISSUE TITLE
single page app : missing static files are served as default routing 

### ISSUE THREAD

**Issue by dlebedynskyi** [aspnet/Routing#293] opened 2016-03-07 19:51 UTC
as requested by 
https://github.com/aspnet/Routing/issues/47#issuecomment-192126947

@Eilon  it is basically the same as in issue above . in case if you specify constrain 
as  4th paramer you are going go get nothing 

```
 app.UseStaticFiles();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapRoute("Wildcard Routing",
                "{*anything}",
                new { controller = "Home", action = "Index" },
                new { anything = @"^(.*)?$" });
            });
```

result is empty content 
![image](https://cloud.githubusercontent.com/assets/1182917/13581025/e4072b96-e472-11e5-9048-08a1b3b4df8f.png)

if you remove constraint you are going to get your index.cshtml served as content 
example for request https://localhost:44391/dist/styles.css

![image](https://cloud.githubusercontent.com/assets/1182917/13581153/80c5322a-e473-11e5-95bd-0be4618a3417.png)

![image](https://cloud.githubusercontent.com/assets/1182917/13581091/3c84e740-e473-11e5-910b-ab5abc4a0610.png)

FYI file is valid css just renamed to show this defect.

Way to bypass this is to remove completely routing mapping from startup.cs and have it as attribute routing on index action 

```
//startup.cs
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseStaticFiles();
            app.UseStatusCodePages();

            app.UseMvc();
        }
//homeController.cs

 public class HomeController : Controller
    {
        // GET: /<controller>/

        [Route("~/", Name = "default")]
        [Route("~/login", Name = "login")]
        [Route("~/access_denied", Name = "access_denied")]
        [Route("~/app/{*url}", Name = "app")]
        public IActionResult Index()
        {
            return View();
...

```

tested on Kestrel and iis express with `1.0.0-rc1-update1 coreclr x64          win 7`

**Comment by ryanbrandenburg** [comment] 2016-03-29 22:07
Hello @dlebedynskyi, could you confirm that this still reproduces for you?

If it does could you post a full reproduction project either as a zip or a github repo? I tried to reproduce it [here](https://github.com/aspnet/Mvc/tree/rybrande/WildcardRouting/samples/MvcSandbox) based on what you posted but got the expected behavior of having the content-type be text/css and the value correct.

**Comment by dlebedynskyi** [comment] 2016-03-31 20:55
@ryanbrandenburg will try to do over weekend

**Comment by dlebedynskyi** [comment] 2016-04-04 15:41
@ryanbrandenburg  please take a look at this repo 
https://github.com/dlebedynskyi/AspBug

right now if you restore deps and run app you should see 

```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:5000/dist/style.css".
```
code in startup.js 
```
app.UseStaticFiles();
            app.UseStaticFiles();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");
                // this gives Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:5000/dist/style.css".

                routes.MapRoute("Wildcard Routing",
                "{*anything}",
                new { controller = "Home", action = "Index" });
            });

````

expected 404 instead of text/plain 
if you *rename dist/style_.css to dist/style.css* - everything is fine and stylesheet is served as expected. 

2nd test is to change routing to 
```
routes.MapRoute("Wildcard Routing",
                "{*anything}",
                new { controller = "Home", action = "Index" },
                new { anything = @"^(.*)?$" })
``` 
result is same. 
**Expected behavior - getting 404 on static files served from wwwroot folder. **

some stuff that may help.
tested on window 10. 
`dnx version   1.0.0-rc1-update1 coreclr x64          win             core`

dnx console log 
```
C:\Code\AspBug\src\AspBug> dnx web
Hosting environment: DEVELOPMENT
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method AspBug.Controllers.HomeController.Index with arguments () - ModelState is Valid'
info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\lebedinskyd\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action AspBug.Controllers.HomeController.Index in 0.0687ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0906ms 200 text/html; charset=utf-8
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/style.css
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method AspBug.Controllers.HomeController.Index with arguments () - ModelState is Valid'
info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action AspBug.Controllers.HomeController.Index in 0ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0ms 200 text/html; charset=utf-8
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/favicon.ico
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method AspBug.Controllers.HomeController.Index with arguments () - ModelState is Valid'
info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action AspBug.Controllers.HomeController.Index in 0.0015ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0015ms 200 text/html; charset=utf-8
```

**Comment by ryanbrandenburg** [comment] 2016-04-04 18:15
@dlebedynskyi that repo only contains .gitignore and .gitattributes.

**Comment by dlebedynskyi** [comment] 2016-04-05 13:18
@ryanbrandenburg  my bad. check now pls

**Comment by ryanbrandenburg** [comment] 2016-04-05 19:42
@dlebedynskyi your `_Layout.cshtml` is looking for `~/dist/style.css`, but the file you have is `wwwroot/dist/style_.css` (notice the extra `_` there). Your routes performed as expected, since it didn't have a "dist/style_.css" it used your wildcard route (rather than returning a 404), which returns a type of text/html. If you either change your cshtml or the name of your file it should all work.

As a bit of an aside, this kind of thing is one of the reasons why having a "catch everything else" route is dangerous. I would encourage you to consider other ways of accomplishing whatever you're trying to achieve there.

**Comment by dlebedynskyi** [comment] 2016-04-05 20:35
@ryanbrandenburg  well this is actually the bug. 

>if you *rename dist/style.css to dist/style.css* _- everything is fine and stylesheet is served as expected.

**Problem is with missing files.  not with valid path **
it is expected to get 404 for  static file  instead of having routing go throw asp.mvc.

**Comment by ryanbrandenburg** [comment] 2016-04-05 23:20
If I understand you correctly then, you're expecting that when you go looking for something "served from the wwwroot" and don't find it you should get 404, even if there is a catch all route?

If that's what you're saying then we're still working as expected. There's no way to know for sure  when someone looks for "dist/style_.css" if they're expecting it from wwwroot or from an MVC route. We only know when things are from wwwroot because we find them in wwwroot, otherwise we can't be sure.

If you want to get 404's for wwwroot requests and still have a catch-all route (and I still advise against catch-all routes in most cases) then you can put everything in wwwroot in a `static` folder, and add a constraint to your catch-all route which excludes routes starting with `static\`.

If what you were actually complaining about was that a request for a .css file returned text/html then I would point out that (at least for me on chrome) the request Accept header for style.css was "text/css,*/*;q=0.1", so any response type is acceptable.

**Comment by dlebedynskyi** [comment] 2016-04-06 16:44
@ryanbrandenburg  I see that from your point it is all as expected but it still does not solves the problem for developing spa with asp.net back with _layout.cshtml and/or some razor views. 

In fact you are right using catch all route is not a good way of doing things but per fact there is no better. This is problem.

So if nothing changes from asp.net mvc routing side and stays as 'work as expected' client side apps are left with option either do not use asp.net mvc at all or solve bugs as I showed earlier. Any other alternative for spa app problem you see?

**Comment by Eilon** [comment] 2016-05-05 17:01
@SteveSandersonMS ping - you had mentioned you wanted to take a look at this?

**Comment by SteveSandersonMS** [comment] 2016-05-05 17:28
I've hit this issue too. I agree with @ryanbrandenburg that routing is working as expected, but I also agree with @dlebedynskyi that the overall design makes it difficult to build a SPA without getting weird responses instead of 404s for missing static resources.

The best resolution I've come up with so far is the `MapSpaFallbackRoute` helper which I put in the `Microsoft.AspNet.SpaServices` package. See [example usage](https://github.com/aspnet/NodeServices/blob/master/templates/Angular2Spa/Startup.cs#L71) and [source code](https://github.com/aspnet/NodeServices/blob/master/src/Microsoft.AspNet.SpaServices/Routing/SpaRouteExtensions.cs). This is just a slightly refined "catch all" route which excludes requests that look like they are for static resources (specifically, if there appears to be a filename extension in the URL, then this route doesn't match it, so it would be a 404 if not already handled by `UseStaticFiles`).

`MapSpaFallbackRoute` is not a perfect solution, but unless you're willing to configure all your client-side routes in `Startup.cs`, then the server can't in general differentiate between "accidentally missing static resource" and "legit URL that should be handled with client-side routing".

**Comment by Eilon** [comment] 2016-05-05 17:34
@SteveSandersonMS thanks for the info. I'm marking this item as a Discussions item as there is no specific bug.

If folks have specific suggestions on improvements we can make, please log those as new issues and we can discuss.

**Comment by dlebedynskyi** [comment] 2016-05-11 13:26
thanks @SteveSandersonMS . I'll check it out.

**Comment by Mukesh-Joshi** [comment] 2016-10-04 16:48
@dlebedynskyi I faces same issue due to favicon. It keep calling the default route defined in startup. I blocked that via creating a static file middleware. It at least blocked the calls to default route.

**Comment by Mukesh-Joshi** [comment] 2016-10-04 16:53
@SteveSandersonMS I am not sure if it's the correct thread, but I am having a different kind of issue. When I added a route Route[{string1}/{string2}] on my mvc controller's action, and my controller already has a route["ABC/"], my svg icons are taking ABC/svg/abc.svg path.
 
This is only present for the icons which I am loading dynamically through JS. It seems that react component is taking path for icon as svg/abc.svg as as I am expecting two string parameters in my url it matches the route and simply add ABC route in the icon's path.
If I remove even one parameter, it starts working fine as route doesn't match. It's a react component which is loading images dynamically, (I only have this information for now,

**Comment by rynowak** [comment] 2016-10-04 18:33
@Mukesh-Joshi - please open a new issue with a code sample rather than tacking on to existing issues

**Comment by Eilon** [comment] 2017-01-06 04:58
@SergeyBarskiy I think you could use routing with a route that captures some particular pattern, which when it matches will run a middleware component that always returns a 404. Is that essentially what you want?

Not sure what the connection is to the StaticFileOptions class though... ?

**Comment by SergeyBarskiy** [comment] 2017-01-08 21:50
@Eilon True, but it just seems weird to handle static files requests in MVC middleware.  I think adding an option to static files configuration to specify request patterns that must be handled by static files middleware would enable it to throw 404 when a file is missing instead of just not handling the request.

**Comment by Eilon** [comment] 2017-01-09 18:38
The static files middleware doesn't ever return a 404 as far as I know. Usually the only thing that returns a 404 is the host itself, in the case where no other middleware handled the request.

That is, the middleware pipeline works like this:

1. Static files
 * If a static file matches, return it
 * Otherwise, do nothing and let the next middleware run.
2. MVC
 * If a controller action matches, run it
 * Otherwise, do nothing and let the next middleware run.
3. Some other middleware
 * If a whatever matches, do that thing
 * Otherwise, do nothing and let the next middleware run.
4. Lastly, if it gets down here, no middleware matched, so return a 404.

**Comment by Eilon** [comment] 2017-06-09 22:19
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by Eilon** 2017-06-09 22:19 UTC
